package calc_val;


/**
* calc_val/calcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Wednesday, April 27, 2022 3:53:05 PM IST
*/

abstract public class calcHelper
{
  private static String  _id = "IDL:calc_val/calc:1.0";

  public static void insert (org.omg.CORBA.Any a, calc_val.calc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static calc_val.calc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (calc_val.calcHelper.id (), "calc");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static calc_val.calc read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_calcStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, calc_val.calc value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static calc_val.calc narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calc_val.calc)
      return (calc_val.calc)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calc_val._calcStub stub = new calc_val._calcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static calc_val.calc unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calc_val.calc)
      return (calc_val.calc)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calc_val._calcStub stub = new calc_val._calcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
