package calc_val;


/**
* calc_val/calcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Wednesday, April 27, 2022 3:53:05 PM IST
*/

public interface calcOperations 
{
  double addfn (double a, double b);
  double subfn (double a, double b);
  double mulfn (double a, double b);
  double divfn (double a, double b);
} // interface calcOperations
