package calc_val;


/**
* calc_val/calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Wednesday, April 27, 2022 3:53:05 PM IST
*/

public interface calc extends calcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calc
