package calc_val;


/**
* calc_val/calcPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Wednesday, April 27, 2022 3:53:05 PM IST
*/

public abstract class calcPOA extends org.omg.PortableServer.Servant
 implements calc_val.calcOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addfn", new java.lang.Integer (0));
    _methods.put ("subfn", new java.lang.Integer (1));
    _methods.put ("mulfn", new java.lang.Integer (2));
    _methods.put ("divfn", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calc_val/calc/addfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.addfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // calc_val/calc/subfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.subfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // calc_val/calc/mulfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.mulfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // calc_val/calc/divfn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.divfn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calc_val/calc:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public calc _this() 
  {
    return calcHelper.narrow(
    super._this_object());
  }

  public calc _this(org.omg.CORBA.ORB orb) 
  {
    return calcHelper.narrow(
    super._this_object(orb));
  }


} // class calcPOA
